experiment:
  exp_dir: experiments/
  exp_name: resume
  seed: 42

task: named-entity-recognition

dataset:
  data_file:
    train: '/home/wp/wenpei/wenpei/AdaSeq-master/data/CH_ner/train.txt'
    valid: '/home/wp/wenpei/wenpei/AdaSeq-master/data/CH_ner/dev.txt'
    test: '/home/wp/wenpei/wenpei/AdaSeq-master/data/CH_ner/test.txt'

  data_type: json_spans
  delimiter: ' '
  labels:
    type: count_span_labels

preprocessor:
  type: span-extraction-preprocessor
  max_length: 500

data_collator: SpanExtractionDataCollatorWithPadding

model:
  type: global-pointer-model
  embedder:
    model_name_or_path: /home/wp/wenpei/wenpei/thirdwork/xlm_roberta_large
  token_ffn_out_width: 64
  word_dropout: 0.1

train:
  max_epochs: 10
  dataloader:
    batch_size_per_gpu: 16
  optimizer:
    type: AdamW
    lr: 5.0e-5
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 10

evaluation:
  dataloader:
    batch_size_per_gpu: 64
  metrics: 
  - span-extraction-metric
  - type: ner-dumper
  - model_type: span_based
  - dump_format: jsonline
