experiment:
  exp_dir: ../AdaSeq-master/experiments1
  exp_name: gp_xlmroberta_large3
  seed: 
      - 42
      - 43
      - 44
      - 45
      - 46

task: named-entity-recognition

dataset:
  data_file:
    test: ../AdaSeq-master/preprocessing/20250625data_test.json
    train: ../AdaSeq-master/preprocessing/20250625data_train.json
    valid: ../AdaSeq-master/preprocessing/20250625data_test.json
  data_type: json_spans
  delimiter: ' '
  labels:
    type: count_span_labels

preprocessor:
  type: span-extraction-preprocessor
  max_length: 500

data_collator: SpanExtractionDataCollatorWithPadding

model:
  type: global-pointer-model
  embedder:
    model_name_or_path: ../thirdwork/xlm_roberta_large
    transformer_kwargs:
      trust_remote_code: true
  token_ffn_out_width: 64
  word_dropout: 0.1

train:
  max_epochs: 
            - 15
            # - 20
  dataloader:
    batch_size_per_gpu: 16
  optimizer:
    type: AdamW
    lr: 
      # - 5.0e-5
      # - 4.5e-5
      - 4.0e-5
      # - 3.5e-5
      - 3.0e-5
      # - 2.5e-5
      # options: 
      # # gradient cumulative interval, default 1
      #   cumulative_iters: 2
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters:
              #  - 5
              #  - 7
              #  - 15
               - 10


evaluation:
  dataloader:
    batch_size_per_gpu: 64
  metrics:
    - type: span-extraction-metric
    - type: ner-dumper
      model_type: span_based
      dump_format: jsonline
