experiment:
  exp_dir: experiments/
  exp_name: cfet
  seed: 42

task: entity-typing

dataset:
  data_file:
    train: 'https://www.modelscope.cn/api/v1/datasets/izhx404/cfet/repo/files?Revision=master&FilePath=train.json'
    valid: 'https://www.modelscope.cn/api/v1/datasets/izhx404/cfet/repo/files?Revision=master&FilePath=dev.json'
    test: 'https://www.modelscope.cn/api/v1/datasets/izhx404/cfet/repo/files?Revision=master&FilePath=test.json'
  tokenizer: char
  labels:
    type: count_span_labels

preprocessor:
  type: multilabel-span-typing-preprocessor
  model_dir: sijunhe/nezha-cn-base
  max_length: 500

data_collator: MultiLabelSpanTypingDataCollatorWithPadding

model:
  type: multilabel-span-typing-model
  embedder:
    model_name_or_path: sijunhe/nezha-cn-base
  dropout: 0.1

train:
  max_epochs: 50
  dataloader:
    batch_size_per_gpu: 16
  optimizer:
    type: AdamW
    lr: 5.0e-5
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 50

evaluation:
  dataloader:
    batch_size_per_gpu: 32
  metrics: typing-metric
