experiment:
  exp_dir: experiments/
  exp_name: ud2

task: part-of-speech

dataset:
  data_file: 'https://www.modelscope.cn/api/v1/datasets/izhx404/ud1_pos/repo/files?Revision=master&FilePath=ud2.zip'
  data_type: conll

preprocessor:
  type: sequence-labeling-preprocessor
  model_dir: babert-base
  max_length: 256
  bio2bioes: true

data_collator: SequenceLabelingDataCollatorWithPadding

model:
  type: sequence-labeling-model
  embedder:
    model_name_or_path: babert-base
  dropout: 0.1
  use_crf: true

train:
  max_epochs: 30
  dataloader:
    batch_size_per_gpu: 32
  optimizer:
    type: AdamW
    lr: 2.0e-5
  lr_scheduler:
    type: LinearLR
    start_factor: 1.0
    end_factor: 0.0
    total_iters: 30

evaluation:
  dataloader:
    batch_size_per_gpu: 128
  metrics:
    - type: ner-metric
    - type: ner-dumper
      model_type: sequence_labeling
      dump_format: conll
